"""Type stubs for the compiled extension module.

The generator exposes one method per formatter; their names and signatures mirror
Faker's and are checked by tests/compat/test_api.py. They are reached dynamically
through ``Faker``/``Generator``, so they are typed here as ``Any`` rather than
duplicated — proxy.pyi carries the per-formatter signatures.
"""

from typing import Any

__version__: str
LOCALES: list[str]

class ParseError(ValueError): ...

class Generator:
    def __init__(self, locale: str = ..., seed: int | None = ...) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __copy__(self) -> Generator: ...
    def __deepcopy__(self, memo: Any) -> Generator: ...
    @property
    def _locale(self) -> str: ...
    @property
    def _use_weighting(self) -> bool: ...
    @_use_weighting.setter
    def _use_weighting(self, value: bool) -> None: ...
    @staticmethod
    def _formatter_names() -> list[str]: ...
    def _uniform(self, a: float, b: float) -> float: ...
    def _random(self) -> float: ...
    def _chance(self, percent: int) -> bool: ...
    def seed_instance(self, seed: int) -> None: ...
