#!/usr/bin/env python3
"""Generate ``python/rusty_faker/proxy.pyi`` from the v1 formatter surface.

Signatures are read from the pinned Faker rather than from rusty_faker itself: the
compat suite (``tests/compat/test_api.py``) asserts the two match, so Faker is the
authoritative description of the API, and the stub can be regenerated even when the
extension is not importable.

Usage: .venv/bin/python tools/generate_stubs.py [--check]
"""

from __future__ import annotations

import argparse
import inspect
import pathlib
import sys

import faker

V1_PROVIDER_MODULES = ("person", "address", "internet", "company", "lorem", "phone_number", "date_time")

HEADER = '''"""Type stubs for the formatters rusty-faker implements.

Generated by tools/generate_stubs.py from Faker {version}; do not edit by hand.
Formatters not listed here resolve through ``Faker.__getattr__`` and are typed ``Any``.
"""

import collections
import datetime
from typing import Any, Callable, Collection, Iterator, List, Sequence, Tuple, TypeVar

from rusty_faker.generator import Generator
from rusty_faker.providers import BaseProvider

T = TypeVar("T")

class UniqueProxy:
    def __getattr__(self, name: str) -> Any: ...
    def clear(self) -> None: ...

class OptionalProxy:
    def __getattr__(self, name: str) -> Any: ...

class Faker:
    def __init__(
        self,
        locale: str | Sequence[str] | dict[str, int | float] | None = ...,
        providers: list[str] | None = ...,
        generator: Generator | None = ...,
        includes: list[str] | None = ...,
        use_weighting: bool = ...,
        **config: Any,
    ) -> None: ...
    def __getitem__(self, locale: str) -> Generator: ...
    def __getattr__(self, attr: str) -> Any: ...
    @property
    def unique(self) -> UniqueProxy: ...
    @property
    def optional(self) -> OptionalProxy: ...
    @property
    def locales(self) -> list[str]: ...
    @property
    def weights(self) -> list[int | float] | None: ...
    def seed_instance(self, seed: Any = ...) -> None: ...
    @classmethod
    def seed(cls, seed: Any = ...) -> None: ...
    def add_provider(self, provider: BaseProvider | type[BaseProvider]) -> None: ...
    def get_formatter_names(self) -> list[str]: ...
'''


def v1_formatters() -> list[tuple[str, object]]:
    """Public formatters Faker exposes for the providers rusty-faker implements."""
    fake = faker.Faker("en_US")
    found: dict[str, object] = {}
    for provider in fake.get_providers():
        module = type(provider).__module__
        in_scope = module == "faker.providers" or any(f"faker.providers.{m}" in module for m in V1_PROVIDER_MODULES)
        if not in_scope:
            continue
        for cls in type(provider).__mro__:
            if not cls.__module__.startswith("faker.providers"):
                continue
            if cls.__module__ != "faker.providers" and not any(
                f"faker.providers.{m}" in cls.__module__ for m in V1_PROVIDER_MODULES
            ):
                continue
            for name, member in vars(cls).items():
                if not name.startswith("_") and callable(member) and name not in found:
                    found[name] = member
    return sorted(found.items())


def render(name: str, func: object) -> str | None:
    try:
        sig = inspect.signature(func)
    except (TypeError, ValueError):
        return None
    params = []
    for i, p in enumerate(sig.parameters.values()):
        if i == 0 and p.name == "self":
            params.append("self")
            continue
        text = p.name
        if p.kind is p.VAR_POSITIONAL:
            text = f"*{p.name}"
        elif p.kind is p.VAR_KEYWORD:
            text = f"**{p.name}"
        if p.annotation is not p.empty:
            text += f": {inspect.formatannotation(p.annotation)}"
        if p.default is not p.empty:
            text += " = ..." if p.annotation is p.empty else " = ..."
        params.append(text)
    ret = "Any" if sig.return_annotation is sig.empty else inspect.formatannotation(sig.return_annotation)
    line = f"    def {name}({', '.join(params)}) -> {ret}: ..."
    return line.replace("~", "")


def build() -> str:
    lines = [HEADER.format(version=faker.VERSION)]
    skip = {"seed", "seed_instance", "add_provider", "get_formatter_names"}
    for name, func in v1_formatters():
        if name in skip:
            continue
        rendered = render(name, func)
        if rendered:
            lines.append(rendered)
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the checked-in stub is stale")
    args = parser.parse_args()

    out = pathlib.Path(__file__).resolve().parent.parent / "python" / "rusty_faker" / "proxy.pyi"
    generated = build()
    if args.check:
        current = out.read_text() if out.exists() else ""
        if current != generated:
            print(f"{out} is stale; re-run tools/generate_stubs.py", file=sys.stderr)
            return 1
        print(f"{out} is up to date")
        return 0
    out.write_text(generated)
    print(f"wrote {out} ({generated.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
